version: '3.8'

services:
  app:
    image: openjdk:21-jdk-slim
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gerenciador
      SPRING_DATASOURCE_USERNAME: gerenciador
      SPRING_DATASOURCE_PASSWORD: gerenciador
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: gerenciador
      POSTGRES_USER: gerenciador
      POSTGRES_PASSWORD: gerenciador
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: