version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: gerenciador
      POSTGRES_USER: gerenciador
      POSTGRES_PASSWORD: gerenciador
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgresql-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gerenciador
      SPRING_DATASOURCE_USERNAME: gerenciador
      SPRING_DATASOURCE_PASSWORD: gerenciador
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - postgresql-network

networks:
  postgresql-network:
    driver: bridge

volumes:
  postgres_data: